---
fw_ports:
  - 10250/tcp         # kubelet
  - 10256/tcp         # kube-proxy health
  - 30000-32767/tcp   # NodePort
  - 8472/udp          # VXLAN de Cilium
  - 4240/tcp          # Cilium health checks entre nodos
  - 4244/tcp          # Hubble server (agente <- Hubble Relay, entre nodos)
